name: Crear Mapa de Minecraft con BlueMap
run-name: Crear Mapa 🚀
on: 
  push:
    branches: [ develop ]
jobs:
  Creando-Mapa:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar Mapa
        uses: actions/checkout@v4
      - name: Installar java 21 #https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Descargar última versión de BlueMap
        run: |
          #!/bin/bash

          # Obtener la URL del último release que contiene la palabra "cli"
          latest_release=$(curl -s https://api.github.com/repos/BlueMap-Minecraft/BlueMap/releases/latest | jq -r '.assets[] | select(.name | contains("cli")) | .browser_download_url')
          
          # Verificar si se encontró un release con la palabra "cli"
          if [ -z "$latest_release" ]; then
            echo "No se encontró un release con la palabra 'cli'"
            exit 1
          fi
          
          # Descargar el archivo del release
          curl -L -o bluemap-cli-latest.jar $latest_release
          
          # Descomprimir el archivo descargado
          #unzip bluemap-cli-latest.zip -d bluemap
      - name: Restaurar caché de world
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./config
            ./data
            ./web
          key: ${{ runner.os }}-world-cache
      - name: Instalar Dependencias BlueMap
        if: ${{ !hashFiles('web/**') }}
        run: |
          #!/bin/bash
          
          echo "Instalando Dependencias BlueMap"
          java -jar bluemap-cli-latest.jar -r || true
      - name: Configurar BlueMap
        if: ${{ !hashFiles('config/**') }}
        run: |
          #!/bin/bash
          
          echo "Configurando BlueMap"
          
          # Nombre del archivo
          archivo="config/core.conf"

          # Reemplazar el texto
          sed -i 's/accept-download: false/accept-download: true/g' "$archivo"
      - name: Crear Mapa
        run: |
          #!/bin/bash

          echo "Creando Mapa"
          java -jar bluemap-cli-latest.jar -r
      - name: Guardar caché de world
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./config
            ./data
            ./web
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
      - name: Agregar llave SSH
        run: |
          #!/bin/bash
          
          echo "Agregando llave SSH"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
      - name: Conexión SSH a minecraft.nujev.com
        run: |
          #!/bin/bash

          echo "Conectándose a minecraft.nujev.com"
          rsync -avz --exclude='.git*' --delete ./web/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:web/ --rsync-path="sudo rsync"

          #scp -i ~/.ssh/id_rsa -o "StrictHostKeyChecking no" -r ./web/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:web/